---
version: 2.1

orbs:
  slack: circleci/slack@4.1.3
  prodsec: snyk/prodsec-orb@1

parameters:
  poetry-version:
    type: string
    # pinned due to poetry issues on circleci
    # https://github.com/python-poetry/poetry/issues/7184#
    default: "1.2.2"

defaults_python: &defaults_python
  resource_class: small
  docker:
    - image: cimg/python:3.12.1

executors:
  python310:
    docker:
      - image: "cimg/python:3.10"
  python39:
    docker:
      - image: "cimg/python:3.9"
  python38:
    docker:
      - image: "cimg/python:3.8"
  python37:
    docker:
      - image: "cimg/python:3.7"
commands:
  install_poetry:
    description: Pin poetry installed version (downgrades version when needed)
    steps:
      - run: poetry self update 1.2.2
jobs:
  security-scans:
    <<: *defaults_python
    steps:
      - prodsec/security_scans:
          mode: gate
  test:
    description: Run Tests for a specific python version
    parameters:
      executor_name:
        type: executor
    executor: << parameters.executor_name >>
    working_directory: ~/project
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install Poetry
          command: >
            curl -sSL https://install.python-poetry.org
            | POETRY_VERSION=<<pipeline.parameters.poetry-version>> python3 -
      - run:
          name: Install dependencies and project in dev mode
          command: poetry install
      - run:
          name: Run tests
          command: poetry run pytest
      - security-scans

  build_and_release:
    description: Build and release new version of the package to PyPi
    executor: python39
    working_directory: ~/project
    steps:
      - checkout:
          path: ~/project
      - install_poetry
      - run:
          name: Configure Poetry PyPi token
          command: |
              poetry config pypi-token.testpypi ${POETRY_PYPI_TOKEN_PYPI}
      # Use `poetry publish` to Publish the package using username and password from CircleCI environment variables
      # Which can be configured inside CircleCI's interface
      - run:
          name: Release and Publish to PyPI
          # Rely on POETRY_PYPI_TOKEN_PYPI ENV variable
          command: |
              poetry publish --build --no-interaction
      - slack/notify:
          channel: sec-eng-red-alerts
          event: fail
          template: basic_fail_1

workflows:
  version: 2
  test_and_release:
    jobs:
      - test:
          name: Run Tests - python 3.10
          executor_name: python310
          context: snyk-security-rnd
          filters:
            branches:
              ignore: main
      - test:
          name: Run Tests - python 3.9
          executor_name: python39
          context: snyk-security-rnd
          filters:
            branches:
              ignore: main
      - test:
          name: Run Tests - python 3.8
          executor_name: python38
          context: snyk-security-rnd
          filters:
            branches:
              ignore: main
      - test:
          name: Run Tests - python 3.7
          executor_name: python37
          context: snyk-security-rnd
          filters:
            branches:
              ignore: main
      - build_and_release:
          name: Build and Release a new version to PyPI
          context:
            - snyk-bot-slack
          requires:
            - Run Tests - python 3.10
            - Run Tests - python 3.9
            - Run Tests - python 3.8
            - Run Tests - python 3.7
          filters:
            branches:
              only: main
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: sec-eng-deployments      

